<a href="https://colab.research.google.com/github/sharadnatarajSJSU/Basic_tensorflow_operations/blob/main/CMPE_258_assignment_2_part_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Fundamentals using PyTorch

In [3]:
import torch

Creating a tensor object

In [5]:
a=torch.ones(3)
a

tensor([1., 1., 1.])

Indexing

In [8]:
a=torch.tensor([1,2,3,4,5])

In [9]:
a[1]

tensor(2)

converting to float. Type Casting

In [10]:
a=torch.tensor([1,2,3,4,5]).float()

In [11]:
a[1]

tensor(2.)

In [13]:
a.shape

torch.Size([5])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points.shape

torch.Size([3, 2])

Tensor storage

In [17]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [18]:
points_storage = points.storage()


In [19]:
points_storage[0]

4.0

storage can be used to index tensors manually by specifying offset and stride

In [20]:
points_storage[0] = 5

In [21]:
points

tensor([[5., 1.],
        [5., 3.],
        [2., 1.]])

changing the value using the storage index changes the tensor. Can also be used using the code below.

In [23]:
points.storage()[0]

5.0

Tensors are stored in continuous memory. Offset is the index that corresponds to the first element of the tensor.The stride is the number of elements in the storage that need to be skipped to obtain the next element along each dimension.

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()


2

In [27]:
second_point

tensor([5., 3.])

In [28]:
points.stride()

(2, 1)

Sun tensors- tensor with one less dimension. Uses the same tensor rather than creating a new one. Hence changing the sub tensor will change the original tensor

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

Tensor clone

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
second_point

tensor([10.,  3.])

Transpose of tensor

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [33]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

No change in tensor. Just changes in stride 

In [38]:
id(points.storage()) == id(points_t.storage())


True

In [40]:
points.stride()

(2, 1)

In [39]:
points_t.stride()

(1, 2)

can also be performed using einsum

In [41]:
points_t = torch.einsum("ij->ji",points)

In [42]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [43]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

For higher dimenssion tensor the indexes can be specified for transpose

In [45]:
some_t = torch.ones(3, 4, 5)
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [46]:
some_t.shape

torch.Size([3, 4, 5])

Flipping the 0th dimenssion and the 2nd

In [47]:
transpose_t = some_t.transpose(0, 2)

In [49]:
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [48]:
transpose_t.shape

torch.Size([5, 4, 3])

In [50]:
some_t.stride()

(20, 5, 1)

In [51]:
transpose_t.stride()

(1, 5, 20)

Multiplication using einsum in pytorch

In [53]:
A = torch.tensor([[1,2,3],[4,5,6]])

In [55]:
B = torch.tensor([[4,5],[1,2],[3,6]])

In [56]:
m_mul = torch.einsum('ij,jk->ik',A,B)

In [57]:
m_mul

tensor([[15, 27],
        [39, 66]])