<a href="https://colab.research.google.com/github/sharadnatarajSJSU/Basic_tensorflow_operations/blob/main/CMPE_258_assignment_2_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

#Displaying basic types of tensors

Scalar tensor or rank 0 

In [2]:
tensor_0 = tf.constant(8)
print(tensor_0)

tf.Tensor(8, shape=(), dtype=int32)


rank 1, Rank 2 and rank 3 Tensors

In [3]:
print("rank 1 tensor")
tensor_1 = tf.constant([1.0,3.2,4.5,6.8])
print(tensor_1)

rank 1 tensor
tf.Tensor([1.  3.2 4.5 6.8], shape=(4,), dtype=float32)


In [4]:
print("rank 2 tensor")
tensor_2 = tf.constant([[2,2],
                        [2,1],
                        [3,6],
                        [4,8],
                        [5,11]],)
print(tensor_2)

rank 2 tensor
tf.Tensor(
[[ 2  2]
 [ 2  1]
 [ 3  6]
 [ 4  8]
 [ 5 11]], shape=(5, 2), dtype=int32)


In [5]:
print("rank 3 tensor")
tensor_3 = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(tensor_3)

rank 3 tensor
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


Converting tensor 3 to ndarray

In [6]:
print(np.array(tensor_3))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


#Indexing

In [7]:
tensor_1[0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

Automatically converts to numpy array

Everything from first element

In [8]:
tensor_1[0 :]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1. , 3.2, 4.5, 6.8], dtype=float32)>

Everything from 2nd to 4th

In [9]:
tensor_1[1 :4]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.2, 4.5, 6.8], dtype=float32)>

Every other element

In [10]:
tensor_1[: : 2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1. , 4.5], dtype=float32)>

Multi axis indexing

In [11]:
tensor_2[1,1]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Explicit convertion using .numpu() function

In [12]:
print("Second row:", tensor_2[1, :].numpy())
print("Second column:", tensor_2[:, 1].numpy())
print("Last row:", tensor_2[-1, :].numpy())
print("First item in last column:", tensor_2[0, -1].numpy())
print("Skip the first row:")
print(tensor_2[1:, :].numpy(), "\n")

Second row: [2 1]
Second column: [ 2  1  6  8 11]
Last row: [ 5 11]
First item in last column: 2
Skip the first row:
[[ 2  1]
 [ 3  6]
 [ 4  8]
 [ 5 11]] 



Rank 3 tensor

In [13]:
print(tensor_3[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


Reshaping Tensors

In [14]:
tensor_3.shape

TensorShape([3, 2, 5])

In [15]:
tensor_3_reshaped = tf.reshape(tensor_3,[10,3])

In [16]:
tensor_3_reshaped.shape

TensorShape([10, 3])

In [17]:
tensor_3

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [18]:
tensor_3_reshaped

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]], dtype=int32)>

Broadcasting

In [19]:
new_tensor = tf.multiply(tensor_3,2)

In [20]:
new_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38]],

       [[40, 42, 44, 46, 48],
        [50, 52, 54, 56, 58]]], dtype=int32)>

In [21]:
tensor_2

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 2,  2],
       [ 2,  1],
       [ 3,  6],
       [ 4,  8],
       [ 5, 11]], dtype=int32)>

In [22]:
tensor_2.shape

TensorShape([5, 2])

In [23]:
tensor_2_3 = tf.ones(shape=[5,2],dtype= tf.dtypes.int32)


In [24]:
new_tensor = tf.multiply(tensor_2,tensor_2_3)

Multiplied with ones. So should get the same tensor

In [25]:
new_tensor

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 2,  2],
       [ 2,  1],
       [ 3,  6],
       [ 4,  8],
       [ 5, 11]], dtype=int32)>

Ragged tensor

In [26]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [27]:
ragged_tensor = tf.ragged.constant(ragged_list)

In [28]:
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


Storing strings in Tensors

In [29]:
tensor_strings = tf.constant(["CMPE 258",
                                 "Deep Learning",
                                 "SJSU"])

In [30]:
tensor_strings.shape

TensorShape([3])

Shape is 3 as it is a rank 1 tensor. The dimenssions of the strings are not considered as tensor shape

In [31]:
print(tensor_strings)

tf.Tensor([b'CMPE 258' b'Deep Learning' b'SJSU'], shape=(3,), dtype=string)


#Customization Basics

tf.add, tf.square

In [32]:
print(tf.add(6, 2))
print(tf.add([6, 2], [3, 4]))
print(tf.square(25))
print(tf.reduce_sum([1, 6, 3]))

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([9 6], shape=(2,), dtype=int32)
tf.Tensor(625, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


using the math operator '+'

In [33]:
print(tf.square(5) + tf.square(12))

tf.Tensor(169, shape=(), dtype=int32)


As tensors can be considered as matrices we can perform matrix multiplation using tf.matmul

In [34]:
m_mul = tf.matmul([[1,2]], [[2, 3],
                          [3,3],])
print(m_mul)
print(m_mul.shape)
print(m_mul.dtype)

tf.Tensor([[8 9]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


#Using EinSum to perform operations on tensors

In [38]:
def matmul(a,b): return tf.einsum('ik,kj->ij', a, b)

In [36]:
tensor_a =tf.constant([[1,2]])
tensor_b =tf.constant([[2, 3],
                          [3,3],])

In [39]:
tensor_matmul = matmul(tensor_a,tensor_b)

In [40]:
tensor_matmul

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[8, 9]], dtype=int32)>